using System.Collections.Generic;

namespace LTF.App.Localization;

/// <summary>
/// The English string pack — the game's UI language (ROADMAP Faz 3). One entry per key in
/// <see cref="StringKeys"/>; the coverage test proves there are no gaps. A Turkish pack of the same
/// shape can be added later without touching any View (ADR-0026 / ROADMAP M19).
/// </summary>
public static class EnglishStrings
{
    public static readonly IReadOnlyDictionary<string, string> Values = new Dictionary<string, string>
    {
        [StringKeys.NavPaddockHub] = "PADDOCK HUB",
        [StringKeys.NavDrivers] = "DRIVERS",
        [StringKeys.NavRndFacilities] = "R&D & FAC.",
        [StringKeys.NavCarsPowerUnit] = "CARS & PU",
        [StringKeys.NavStaff] = "STAFF",
        [StringKeys.NavFinance] = "FINANCE",
        [StringKeys.NavBoardSponsors] = "BOARD & SPON.",
        [StringKeys.NavStandings] = "STANDINGS",
        [StringKeys.NavCalendar] = "CALENDAR",
        [StringKeys.NavDatabase] = "DATABASE",
        [StringKeys.NavRecords] = "RECORDS",
        [StringKeys.NavRaceWeekend] = "RACE WEEKEND",
        [StringKeys.NavSettings] = "SETTINGS",
        [StringKeys.NavExitToMenu] = "EXIT TO MENU",

        [StringKeys.SectionNavigation] = "NAVIGATION",
        [StringKeys.SectionRaceDay] = "RACE DAY",

        [StringKeys.TopContinue] = "CONTINUE",
        [StringKeys.TopInbox] = "INBOX",
        [StringKeys.TopSearchPlaceholder] = "Search…",
        [StringKeys.TopCapRoom] = "CAP ROOM",
        [StringKeys.TopBoardConf] = "BOARD CONF",

        [StringKeys.StatusReady] = "Ready.",

        [StringKeys.StateEmptyTitle] = "Nothing here yet",
        [StringKeys.StateLoadingTitle] = "Loading…",
        [StringKeys.StateErrorTitle] = "Something went wrong",
        [StringKeys.StateErrorRetry] = "Retry",

        [StringKeys.DialogConfirm] = "Confirm",
        [StringKeys.DialogCancel] = "Cancel",
        [StringKeys.DialogExitTitle] = "Exit to menu?",
        [StringKeys.DialogExitBody] = "Any unsaved progress will be lost.",

        [StringKeys.MenuTagline] = "TEAM PRINCIPAL",
        [StringKeys.MenuNewCareer] = "NEW CAREER",
        [StringKeys.MenuContinue] = "CONTINUE CAREER",
        [StringKeys.MenuLoadGame] = "LOAD GAME",
        [StringKeys.MenuQuickRace] = "QUICK RACE",
        [StringKeys.MenuSettings] = "SETTINGS",
        [StringKeys.MenuQuit] = "QUIT",

        [StringKeys.NewCareerTitle] = "NEW CAREER",
        [StringKeys.NewCareerBack] = "BACK",
        [StringKeys.NewCareerNext] = "NEXT",
        [StringKeys.NewCareerStart] = "START CAREER",
        [StringKeys.NewCareerConfirmHeading] = "YOU'RE ABOUT TO TAKE CHARGE OF",
        [StringKeys.NewCareerStepCarset] = "STEP 1 OF 4 · CHOOSE A SERIES",
        [StringKeys.NewCareerStepTeam] = "STEP 2 OF 4 · CHOOSE YOUR TEAM",
        [StringKeys.NewCareerStepBoard] = "STEP 3 OF 4 · BOARD OBJECTIVES",
        [StringKeys.NewCareerStepConfirm] = "STEP 4 OF 4 · CONFIRM",

        [StringKeys.BoardHeading] = "The board sets your mandate. Push back with your ambition, and they'll answer.",
        [StringKeys.BoardAmbitionCautious] = "CAUTIOUS",
        [StringKeys.BoardAmbitionBalanced] = "BALANCED",
        [StringKeys.BoardAmbitionAggressive] = "AGGRESSIVE",
        [StringKeys.BoardReactionAccepted] = "The board agrees.",
        [StringKeys.BoardReactionCountered] = "The board counters.",
        [StringKeys.BoardReactionRejected] = "The board holds firm.",

        [StringKeys.LoadGameTitle] = "LOAD GAME",
        [StringKeys.LoadGameEmpty] = "No saved careers yet.",
        [StringKeys.LoadGameLoad] = "LOAD",
        [StringKeys.LoadGameDelete] = "DELETE",
        [StringKeys.LoadGameBack] = "BACK",

        [StringKeys.SettingsTitle] = "SETTINGS",
        [StringKeys.SettingsGameplay] = "GAMEPLAY",
        [StringKeys.SettingsAutosave] = "Autosave after each session",
        [StringKeys.SettingsDifficulty] = "Difficulty",
        [StringKeys.SettingsRaceSpeed] = "Race speed",
        [StringKeys.SettingsAccessibility] = "ACCESSIBILITY",
        [StringKeys.SettingsInterfaceScale] = "Interface scale",
        [StringKeys.SettingsTextSize] = "Text size",
        [StringKeys.SettingsReduceMotion] = "Reduce motion",
        [StringKeys.SettingsHighContrast] = "High-contrast palette",
        [StringKeys.SettingsAudio] = "AUDIO",
        [StringKeys.SettingsMaster] = "Master",
        [StringKeys.SettingsMusic] = "Music",
        [StringKeys.SettingsSfx] = "Effects",
        [StringKeys.SettingsSave] = "SAVE",
        [StringKeys.SettingsBack] = "BACK",
        [StringKeys.SettingsReset] = "RESET",

        [StringKeys.QuickRaceTitle] = "QUICK RACE",
        [StringKeys.QuickRaceCarset] = "SERIES",
        [StringKeys.QuickRaceCircuit] = "CIRCUIT",
        [StringKeys.QuickRaceRun] = "RACE",
        [StringKeys.QuickRaceBack] = "BACK",

        [StringKeys.StandingsConstructors] = "CONSTRUCTORS",
        [StringKeys.StandingsDrivers] = "DRIVERS",
        [StringKeys.CalendarFixture] = "FIXTURE",
        [StringKeys.CalendarTrackProfile] = "TRACK PROFILE",
        [StringKeys.DriversSquadAndProfiles] = "Squad & profiles",
        [StringKeys.DriversSquadList] = "SQUAD LIST",
        [StringKeys.DriversCoreAttributes] = "CORE ATTRIBUTES",
        [StringKeys.DriversProfileDetails] = "DETAILS",
        [StringKeys.DatabaseTabDrivers] = "DRIVERS",
        [StringKeys.DatabaseTabJuniors] = "JUNIORS",
        [StringKeys.DatabaseTabTeams] = "TEAMS",
        [StringKeys.DatabaseColName] = "NAME",
        [StringKeys.DatabaseColNat] = "NAT",
        [StringKeys.DatabaseColAge] = "AGE",
        [StringKeys.DatabaseColTeam] = "TEAM",
        [StringKeys.DatabaseColOvr] = "OVR",
        [StringKeys.DatabaseColPot] = "POT",
        [StringKeys.PaddockSummaryStatus] = "SUMMARY STATUS",
        [StringKeys.PaddockCurrentEvents] = "CURRENT EVENTS",
        [StringKeys.PaddockWccPosition] = "WCC POSITION",
        [StringKeys.PaddockBoardConfidence] = "BOARD CONFIDENCE",
        [StringKeys.PaddockNextSession] = "NEXT SESSION",
        [StringKeys.PaddockNextEvent] = "NEXT EVENT",
        [StringKeys.PaddockGoToRaceWeekend] = "GO TO RACE WEEKEND »",
        [StringKeys.PaddockCriticalDecisions] = "Critical decisions",
        [StringKeys.PaddockHighPriority] = "High priority",
        [StringKeys.PaddockPendingItems] = "Pending items",
        [StringKeys.PaddockDialogue] = "PADDOCK DIALOGUE",
        [StringKeys.PaddockDialogueEmpty] = "No active conversations",
        [StringKeys.PaddockDialogueEmptyBody] = "Driver and board dialogue opens up with the transfer market.",

        [StringKeys.FinanceFinances] = "FINANCES",
        [StringKeys.FinanceBalance] = "Balance",
        [StringKeys.FinanceSeasonBudget] = "Season budget",
        [StringKeys.FinancePrizeMoney] = "Prize money",
        [StringKeys.FinanceSponsorIncome] = "Sponsor income",
        [StringKeys.FinanceCostCap] = "Cost cap",
        [StringKeys.FinanceTotalDebt] = "Total debt",
        [StringKeys.FinanceCredit] = "CREDIT & BANK",
        [StringKeys.FinanceCreditScore] = "CREDIT SCORE",
        [StringKeys.FinanceOfferedRate] = "Offered rate",
        [StringKeys.FinanceCreditLimit] = "Credit limit",
        [StringKeys.FinanceHeadroom] = "Available headroom",
        [StringKeys.FinanceNoBank] = "This series runs no bank — no credit is available.",
        [StringKeys.FinanceLoans] = "LOANS",
        [StringKeys.FinanceNoLoans] = "No outstanding loans",
        [StringKeys.FinanceNoLoansBody] = "The team carries no debt.",
        [StringKeys.FinanceColLender] = "LENDER",
        [StringKeys.FinanceColOutstanding] = "OWED",
        [StringKeys.FinanceColRate] = "RATE",
        [StringKeys.FinanceColLeft] = "LEFT",
        [StringKeys.FinanceColNext] = "NEXT",
        [StringKeys.FinanceSponsors] = "SPONSORS",
        [StringKeys.FinanceNoSponsors] = "No sponsors",
        [StringKeys.FinanceTakeLoan] = "TAKE A LOAN",
        [StringKeys.FinanceBorrowAmount] = "Amount",
        [StringKeys.FinanceBorrowTerm] = "Term (seasons)",
        [StringKeys.FinanceBorrowButton] = "TAKE LOAN",

        [StringKeys.RndFacilities] = "FACILITIES",
        [StringKeys.RndResearch] = "RESEARCH & DEVELOPMENT",
        [StringKeys.RndReadiness] = "Regulation readiness",
        [StringKeys.RndConceptAero] = "Aero concept",
        [StringKeys.RndConceptPowertrain] = "Powertrain concept",
        [StringKeys.RndNodesUnlocked] = "Nodes unlocked",
        [StringKeys.RndProjects] = "ACTIVE PROJECTS",
        [StringKeys.RndNoProjects] = "No active development",
        [StringKeys.RndNoProjectsBody] = "The team is running no development projects.",
        [StringKeys.RndSteerConcept] = "STEER CONCEPT",
        [StringKeys.RndApplyConcept] = "Apply Concept",
        [StringKeys.RndFreezes] = "FIA DEVELOPMENT FREEZE",
        [StringKeys.RaceWeekendNoRace] = "No race has run yet this season.",
        [StringKeys.RaceWeekendTower] = "TIMING TOWER",
        [StringKeys.RaceWeekendEvents] = "RACE EVENTS",
        [StringKeys.RaceWeekendClassification] = "FINAL CLASSIFICATION",
        [StringKeys.RaceWeekendStrategy] = "STARTING STRATEGY",
        [StringKeys.RaceWeekendStartTyre] = "Start tyre",
        [StringKeys.RaceWeekendStartRace] = "START RACE",
        [StringKeys.RaceWeekendTabRace] = "RACE",
        [StringKeys.RaceWeekendTabQualifying] = "QUALIFYING",
        [StringKeys.RaceWeekendRadio] = "TEAM RADIO",
        [StringKeys.RaceWeekendRaceLive] = "RACE LIVE",
        [StringKeys.RaceWeekendPitWall] = "PIT WALL",
        [StringKeys.RaceWeekendCmdBox] = "BOX",
        [StringKeys.RaceWeekendCmdPush] = "PUSH",
        [StringKeys.RaceWeekendCmdExtend] = "EXTEND",
        [StringKeys.RaceWeekendCmdManage] = "MANAGE",

        [StringKeys.RecordsCareerRecord] = "CAREER RECORD",
        [StringKeys.RecordsTabProfiles] = "PROFILES",
        [StringKeys.RecordsTabThisSeason] = "THIS SEASON",
        [StringKeys.RecordsTabAllTime] = "ALL-TIME",
        [StringKeys.RecordsTabHallOfFame] = "HALL OF FAME",
        [StringKeys.RecordsColDriver] = "DRIVER",
        [StringKeys.RecordsColRaces] = "RACES",
        [StringKeys.RecordsColWins] = "WINS",
        [StringKeys.RecordsColPodiums] = "POD",
        [StringKeys.RecordsColPoles] = "POLE",
        [StringKeys.RecordsColTitles] = "TITLES",
        [StringKeys.RecordsColPoints] = "PTS",
        [StringKeys.RecordsComingSoon] = "More record books coming.",
        [StringKeys.RecordsChampions] = "CHAMPIONS",
        [StringKeys.RecordsTrackRecords] = "TRACK RECORDS",
        [StringKeys.RecordsColYear] = "YEAR",
        [StringKeys.RecordsColChampion] = "DRIVERS' CHAMPION",
        [StringKeys.RecordsColConstructor] = "CONSTRUCTOR",
        [StringKeys.RecordsColCircuit] = "CIRCUIT",
        [StringKeys.RecordsColLap] = "LAP TIME",
        [StringKeys.RecordsColHolder] = "HOLDER",
        [StringKeys.RecordsEmptyHistory] = "Complete a season to build the record books.",
        [StringKeys.RecordsSeasonLeaders] = "SEASON LEADERS",
        [StringKeys.RecordsHeadToHead] = "TEAMMATE HEAD-TO-HEAD",
        [StringKeys.RecordsPointsProgression] = "POINTS PROGRESSION",
        [StringKeys.RecordsHthQualifying] = "QUALIFYING",
        [StringKeys.RecordsHthRace] = "RACE",
        [StringKeys.RecordsHthPoints] = "POINTS",
        [StringKeys.RecordsEmptySeason] = "The season's statistics appear once racing is under way.",

        [StringKeys.CarsPerformance] = "CAR PERFORMANCE",
        [StringKeys.CarsOverall] = "OVERALL",
        [StringKeys.CarsEngineSupplier] = "Engine supplier",
        [StringKeys.CarsComponents] = "COMPONENTS",
        [StringKeys.CarsColReliability] = "REL",
        [StringKeys.CarsColUsage] = "USED",
        [StringKeys.CarsColWear] = "WEAR",
        [StringKeys.CarsNoComponents] = "No component pool",
        [StringKeys.CarsNoComponentsBody] = "This series does not track component allocation.",

        [StringKeys.BoardBoard] = "BOARD",
        [StringKeys.BoardOwnership] = "Ownership",
        [StringKeys.BoardFiringRisk] = "Firing risk",
        [StringKeys.BoardMembers] = "BOARD MEMBERS",
        [StringKeys.BoardObjectives] = "SEASON OBJECTIVES",
        [StringKeys.BoardNoBoard] = "No board oversight",
        [StringKeys.BoardNoBoardBody] = "This team is AI-run and carries no board.",

        [StringKeys.StaffSquad] = "TECHNICAL STAFF",
        [StringKeys.StaffFreeAgents] = "FREE AGENTS",
        [StringKeys.StaffColRole] = "ROLE",
        [StringKeys.StaffColSkill] = "SKILL",
        [StringKeys.StaffColSalary] = "SALARY",
        [StringKeys.StaffNoSquad] = "No technical staff",
        [StringKeys.StaffNoPool] = "No free agents available",
    };
}
